version: '3'

services:
   adminer:
      image: adminer:latest
      restart: always
      ports:
         - 8888:8080

   db:
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_PASSWORD: snips
         POSTGRES_USER: snips
         POSTGRES_DB: snips_dev
      ports:
         - 5432:5432
