name:                guack
version:             0.1.0.0
github:              "japiirainen/snipts"
license:             BSD3
author:              "Joona Piirainen"
maintainer:          "joona.piirainen@gmail.com"
copyright:           "2021 Joona Piirainen"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/japiirainen/snipts#readme>

ghc-options:
 - -fplugin=Polysemy.Plugin

default-extensions:
# Recommended for Polysemy
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell

  # Deriving extensions
  - GeneralizedNewtypeDeriving
  - DeriveGeneric

  # Misc
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- servant-server
- servant
- time
- wai
- warp
- bytestring
- http-types
- text
- containers
- polysemy
- polysemy-plugin
- errors
- mtl
- directory
- acid-state
- safecopy

# Swagger UI
- servant-docs
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- swagger2
- lens
- process

library:
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively


executables:
  guack:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively

    dependencies:
    - guack

tests:
  guack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively
    dependencies:
    - guack
    - hspec
    - QuickCheck
    - quickcheck-io
    - hspec-wai
#    - hspec-wai-json
    - wai-extra
