GET http://localhost:4000/health

###
GET http://localhost:4000/me

###
POST http://localhost:4000/register
content-type: application/json

{
    "username": "joona",
    "email": "joona.piirainen@gmail.com",
    "password": "joona123"
}

###
POST http://localhost:4000/refresh-token